# Generated by Django 5.2 on 2025-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tenant_id", models.IntegerField()),
            ],
            options={
                "db_table": "user",
                "unique_together": {("username", "tenant_id")},
            },
        ),
    ]
